---
title: "HW14: Maps"
author: "Alissa Seal"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

### Import Data
```{r}
library(here)
library(raster)
library(sf)
library(tidyverse)
library(ggthemes)
library(patchwork)
library(maptools)
library(ggmap)
library(marmap)
```

### Part 1: Outline Maps

## Outline of the 48 contiguous states
```{r}
usa <- map_data(map= "state")
```

## Outline of just Missouri
```{r}
us_missouri <- map_data (map = "state",
                         region = "missouri")
```

## OUtline of Alabama, Florida, Mississippi, and North Carolina
```{r}
us_other <- subset(x= usa, 
                   subset= region %in% c("alabama",
                                         "florida",
                                         "mississippi",
                                         "north carolina"))
```

```{r}
str(usa)
```

## Map of 4 non-Missouri states
```{r}
ggplot()+
  geom_polygon(data = us_other, 
               aes(x=long, 
                   y= lat,
                   group=group),
               fill= "gray")
```

## Add Missouri with emphasis 
```{r}
ggplot() +
geom_polygon(data = us_other,
             aes(x = long,
                 y = lat,
                 group = group),
             fill = "gray") +
geom_polygon(data = us_missouri,
             aes(x = long, y = lat,
                 group = group),
             fill = "black")
```

## Outline of all 48 states
```{r}
ggplot() +
geom_polygon(data = us_other,
             aes(x = long,
                 y = lat,
                 group = group),
             fill = "gray") +
geom_polygon(data = us_missouri,
             aes(x = long, y = lat,
                 group = group),
             fill = "black") +
geom_polygon(data = usa,
             aes(x=long,
                 y = lat,
                 group = group),
             fill = NA,
             color = "black")
```
## Add the filled states first so that the black outline of all
## States are overlaid on top
```{r}
us_map <- ggplot() +
geom_polygon(data = us_other,
             aes(x = long,
                 y = lat,
                 group = group),
             fill = "gray") +
geom_polygon(data = us_missouri,
             aes(x = long, y = lat,
                 group = group),
             fill = "black") +
geom_polygon(data = usa,
             aes(x=long,
                 y = lat,
                 group = group),
             fill = NA,
             color = "black") +
theme_map() +
coord_fixed(1.3)
us_map
```

## Missouri Map
```{r}
missouri <- map_data("county", "missouri")
mo_scott <- subset(missouri, subregion %in% c("scott"))
mo_map <- ggplot() +
geom_polygon(data = missouri, aes(x=long, y = lat, group = group), fill = NA, color = "black") +
geom_polygon(data = mo_scott, aes(x = long, y = lat, group = group), fill = "black") +
theme_map() +
coord_fixed(1.3)
mo_map
```

## us_map and a mo_map side by side
```{r}
us_map + mo_map + plot_layout(ncol = 2, widths = c(1.5,1))
```

